/**
 * 自発ループ（v3 観察ループ）の設定カタログ。
 *
 * 対応するコード: chatbot/agent_loops.py `_cycle_plan()`（登録簿）と
 * 各 `_*_cycle` メソッド。**BOT側にサイクルを足したらここにも1行足す。**
 *
 * 既定値はすべてコードの実際の値（.get の第2引数 / モジュール定数）を写している。
 * `fixedNote` はコード側で固定されていて設定できない事実の注記。
 */
import { WEEKDAY_OPTIONS, type Setting, type SettingGroup } from "./types.ts";

/** ループ全体の共通設定 */
const COMMON: Setting[] = [
  {
    path: "proactive.enabled",
    label: "自発的に動く",
    desc: "呼ばれなくても自分から会話を観察して発言するかどうか。すべての自発機能の親スイッチです。",
    kind: "bool",
    default: false,
  },
  {
    path: "proactive.interval_min",
    label: "観察の間隔",
    desc: "何分おきに全サイクルを1周するか。短くすると反応が早くなりますが、その分マシンとAPIを使います。",
    kind: "int",
    default: 30,
    min: 5,
    max: 720,
    unit: "分",
  },
  {
    path: "proactive.daily_quota",
    label: "1日に話しかけてよい回数",
    desc: "自分から発言できる上限。納期の声かけ（nudge）と追跡宣言（track）はこの枠を消費しません。",
    kind: "int",
    default: 3,
    min: 0,
    max: 50,
    unit: "回/日",
    fixedNote:
      "会話で「もっと言っていいよ」と伝えるとDBの値が優先されます（画面の「現在の実効値」を参照）",
  },
  {
    path: "proactive.start_delay_sec",
    label: "起動してから観察を始めるまでの待ち時間",
    desc: "エージェントごとにずらして、起動直後にAIの呼び出しが集中しないようにします。",
    kind: "int",
    default: 120,
    min: 0,
    max: 3600,
    unit: "秒",
  },
  {
    path: "proactive.screen_model",
    label: "下読みに使うモデル",
    desc: "会話の下読み・分析に使う安価なモデル。ほぼ全サイクルとセルフレビューで共有されます。",
    kind: "string",
    default: "claude-haiku-4-5-20251001",
  },
  {
    path: "proactive.scope_note",
    label: "守備範囲の言い聞かせ",
    desc: "「あなたが口を出してよいのはここまで」とAIに伝える文章。専門外に踏み込ませない要になります。",
    kind: "text",
    default: null,
  },
  {
    path: "proactive.exclude_channel_ids",
    label: "観察しないチャンネル",
    desc: "自発発言の対象から外すチャンネルID。自分のホームチャンネルは自動で除外されます。",
    kind: "stringList",
    default: [],
  },
  {
    path: "proactive.handoff",
    label: "専門外の話を振ってよい相手",
    desc: "自分の担当外だと判断したとき、どの同僚AIに引き継ぐか。未設定なら引き継ぎません。",
    kind: "stringList",
    default: [],
  },
  {
    path: "proactive.skeptic",
    label: "発言前の最終監査",
    desc: "自発発言を投稿する直前に、別AIに「本当に言っていいか」を審査させます。オフにすると発言が増え、雑になります。",
    kind: "bool",
    default: true,
  },
  {
    // 注意: パスは必ず .enabled リーフを指す。"proactive.rest" を bool で
    // 指すとトグルがオブジェクトごと true/false に潰す（実際に起きた事故）
    path: "proactive.rest.enabled",
    label: "深夜は休む",
    desc: "指定した時間帯は観察そのものを止めます。コスト削減と、人間らしさの両方のため。",
    kind: "bool",
    default: true,
    children: [
      {
        path: "proactive.rest.start_hour",
        label: "休憩の開始",
        desc: "この時刻から観察を止めます。",
        kind: "hour",
        default: 1,
      },
      {
        path: "proactive.rest.end_hour",
        label: "休憩の終了",
        desc: "この時刻から観察を再開します。日をまたぐ指定もできます。",
        kind: "hour",
        default: 7,
      },
    ],
  },
];

/** サイクル群（_cycle_plan() の登録順） */
const CYCLES: Setting[] = [
  {
    path: "proactive.minutes_channel_id",
    label: "議事録TODO抽出・納期の声かけ",
    desc: "議事録チャンネルを指定すると、新しい議事録からTODOと決定事項を抜き出して追跡し、期日が近づいた担当者に声をかけます。",
    kind: "string",
    default: null,
    fixedNote:
      "声かけの時刻はコード固定（2日前・当日朝・超過）。この2機能は日次枠を消費しません",
  },
  {
    path: "proactive.weekly_report",
    label: "週次レポート",
    desc: "金曜の夕方に「今週こう動きました」を自分のホームチャンネルへ1回だけ投稿します。",
    kind: "bool",
    default: false,
    fixedNote: "投稿時刻は金曜17時以降の最初の観察周期でコード固定",
    children: [
      {
        path: "proactive.dashboard",
        label: "レポートにグラフ画像を添付",
        desc: "数字を横棒グラフのPNGにして添付します。日本語フォントが無い環境では色帯だけになります。",
        kind: "bool",
        default: true,
      },
    ],
  },
  {
    path: "proactive.rescue",
    label: "見捨てられた質問を拾う",
    desc: "24時間誰も答えていない質問を見つけて、代わりに答えます。",
    kind: "tri",
    default: { enabled: false, shadow: true },
  },
  {
    path: "proactive.stale_watch",
    label: "止まった話題の状況確認",
    desc: "動きが止まったチャンネルに「これどうなっていますか？」と様子を聞きます。",
    kind: "tri",
    default: { enabled: false, shadow: true },
    fixedNote: "声かけは8〜20時のみ・1周期1チャンネルまで",
  },
  {
    path: "proactive.homework",
    label: "自己約束の追跡（宿題）",
    desc: "「〇〇やっときます」という発言を黙って拾っておき、後日「あれどうなりました？」と確認します。",
    kind: "tri",
    default: { enabled: false, shadow: true },
    fixedNote: "確認は8〜22時のみ",
    children: [
      {
        path: "proactive.homework.follow_up_days",
        label: "何日後に確認するか",
        desc: "約束を検知してから確認するまでの日数。",
        kind: "int",
        default: 3,
        min: 1,
        max: 60,
        unit: "日後",
      },
      {
        path: "proactive.homework.expire_days",
        label: "追跡をやめるまで",
        desc: "これ以上過ぎた約束はもう掘り返しません。",
        kind: "int",
        default: 14,
        min: 1,
        max: 180,
        unit: "日",
      },
    ],
  },
  {
    path: "proactive.briefing",
    label: "朝のブリーフィング",
    desc: "毎朝1本、今日の期日・予定・重要な未読をまとめてホームチャンネルへ配信します。",
    kind: "tri",
    default: { enabled: false, shadow: true },
    children: [
      {
        path: "proactive.briefing.hour",
        label: "配信時刻",
        desc: "この時刻を過ぎた最初の観察周期で配信します。",
        kind: "hour",
        default: 8,
      },
    ],
  },
  {
    path: "proactive.prep",
    label: "定例会議の事前パック",
    desc: "定例の1時間前に、未完了タスク・直近の決定・前回議事録リンクを議事録チャンネルへ置きます。",
    kind: "tri",
    default: { enabled: false, shadow: true },
    requires: [{ path: "proactive.minutes_channel_id", label: "議事録チャンネルの指定" }],
    children: [
      {
        path: "proactive.prep.weekday",
        label: "定例の曜日",
        desc: "定例会議が開かれる曜日。",
        kind: "weekday",
        default: 4,
        options: WEEKDAY_OPTIONS,
      },
      {
        path: "proactive.prep.hour",
        label: "定例の開始時刻",
        desc: "この1時間前に事前パックを投稿します。",
        kind: "hour",
        default: 19,
      },
    ],
  },
  {
    path: "proactive.event_planner",
    label: "イベントの逆算スケジュール提案",
    desc: "「イベントやります」という決定を検知して、当日から逆算した準備スケジュール案を出します。",
    kind: "tri",
    default: { enabled: false, shadow: false },
  },
  {
    path: "proactive.profiles.enabled",
    label: "人物メモの蓄積",
    desc: "よく発言する人の担当や口ぶりのメモを自動で貯めます。投稿は一切しない静かな処理です。",
    kind: "bool",
    default: false,
    children: [
      {
        path: "proactive.profiles.min_new_messages",
        label: "更新のきっかけ",
        desc: "その人の新しい発言が何件たまったらメモを更新するか。",
        kind: "int",
        default: 20,
        min: 1,
        max: 500,
        unit: "件",
      },
    ],
  },
  {
    path: "proactive.episodes",
    label: "エピソード記憶の同期",
    desc: "決定・完了・イベントを時系列の記憶に貯めます。投稿なしの裏方処理です。",
    kind: "bool",
    default: true,
  },
  {
    path: "proactive.rule_distill.enabled",
    label: "ルールの棚卸し",
    desc: "貯まったルール記憶の重複や時代遅れを週1で見直し、無効化を提案します（✅で承認）。",
    kind: "bool",
    default: false,
    children: [
      {
        path: "proactive.rule_distill.weekday",
        label: "実行する曜日",
        desc: "棚卸しを走らせる曜日。",
        kind: "weekday",
        default: 0,
        options: WEEKDAY_OPTIONS,
      },
      {
        path: "proactive.rule_distill.hour",
        label: "実行時刻",
        desc: "棚卸しを走らせる時刻。",
        kind: "hour",
        default: 10,
      },
    ],
  },
  {
    path: "proactive.selfreview_distill.enabled",
    label: "自己採点の蒸留",
    desc: "自分の回答への自己採点のうち低スコアの共通因子を週1で蒸留し、「心がけ」として次回以降の回答プロンプトに注入します。投稿はしない静かな処理です。",
    kind: "bool",
    default: false,
    fixedNote: "助言は最新の蒸留3件だけが生きます（古いものは自動で差し替え）",
    children: [
      {
        path: "proactive.selfreview_distill.weekday",
        label: "実行する曜日",
        desc: "蒸留を走らせる曜日。",
        kind: "weekday",
        default: 0,
        options: WEEKDAY_OPTIONS,
      },
      {
        path: "proactive.selfreview_distill.hour",
        label: "実行時刻",
        desc: "蒸留を走らせる時刻。",
        kind: "hour",
        default: 9,
      },
    ],
  },
  {
    path: "proactive.pulse.enabled",
    label: "満足度アンケート",
    desc: "月1回、1問だけのアンケートをホームチャンネルに出し、前回の集計も報告します。",
    kind: "bool",
    default: false,
    children: [
      {
        path: "proactive.pulse.day",
        label: "実行日",
        desc: "毎月何日に出すか。",
        kind: "monthday",
        default: 1,
      },
      {
        path: "proactive.pulse.hour",
        label: "実行時刻",
        desc: "何時に出すか。",
        kind: "hour",
        default: 11,
      },
    ],
  },
  {
    path: "proactive.event_watch.enabled",
    label: "イベントの節目ウォッチ",
    desc: "逆算プランが確定したイベントについて、自分の担当分野の節目が近づいたら1回だけ知らせます。",
    kind: "bool",
    default: false,
  },
  {
    path: "proactive.persona_review.enabled",
    label: "人格チューニングの月次提案",
    desc: "行動データから「この人格設定を直すとよい」という案と、使われていないスキルの棚卸しを報告します。",
    kind: "bool",
    default: false,
    children: [
      {
        path: "proactive.persona_review.day",
        label: "実行日",
        desc: "毎月何日に実行するか。",
        kind: "monthday",
        default: 1,
      },
      {
        path: "proactive.persona_review.hour",
        label: "実行時刻",
        desc: "何時に実行するか。",
        kind: "hour",
        default: 12,
      },
    ],
  },
  {
    path: "proactive.auto_discover.enabled",
    label: "自動化ネタの発掘",
    desc: "「毎回手でやっている作業」を記録から探し、自動化を提案します（👍で開発起票へ）。",
    kind: "bool",
    default: false,
    children: [
      {
        path: "proactive.auto_discover.day",
        label: "実行日",
        desc: "毎月何日に実行するか。",
        kind: "monthday",
        default: 2,
      },
      {
        path: "proactive.auto_discover.hour",
        label: "実行時刻",
        desc: "何時に実行するか。",
        kind: "hour",
        default: 11,
      },
    ],
  },
  {
    path: "proactive.outreach.enabled",
    label: "御用聞き",
    desc: "週1で「何かお手伝いできることはありますか？」＋新しくできるようになった事を告知します。",
    kind: "bool",
    default: false,
    children: [
      {
        path: "proactive.outreach.weekday",
        label: "実行する曜日",
        desc: "御用聞きを出す曜日。",
        kind: "weekday",
        default: 0,
        options: WEEKDAY_OPTIONS,
      },
      {
        path: "proactive.outreach.hour",
        label: "実行時刻",
        desc: "御用聞きを出す時刻。",
        kind: "hour",
        default: 10,
      },
    ],
  },
  {
    path: "proactive.kpi.enabled",
    label: "四半期の目標宣言",
    desc: "四半期の初日に、前期の実績と今期の目標を自分で宣言します。",
    kind: "bool",
    default: false,
    children: [
      {
        path: "proactive.kpi.day",
        label: "実行日",
        desc: "四半期初月の何日に実行するか。",
        kind: "monthday",
        default: 1,
      },
      {
        path: "proactive.kpi.hour",
        label: "実行時刻",
        desc: "何時に実行するか。",
        kind: "hour",
        default: 13,
      },
    ],
  },
  {
    path: "proactive.demand_watch.enabled",
    label: "欠員の発見と採用提案",
    desc: "「担当のいない仕事」を月次で見つけ、新しいAIの採用を提案します（管理者の👍で採用）。",
    kind: "bool",
    default: false,
    children: [
      {
        path: "proactive.demand_watch.day",
        label: "実行日",
        desc: "毎月何日に実行するか。",
        kind: "monthday",
        default: 3,
      },
      {
        path: "proactive.demand_watch.hour",
        label: "実行時刻",
        desc: "何時に実行するか。",
        kind: "hour",
        default: 11,
      },
    ],
  },
  {
    path: "proactive.injection_drill.enabled",
    label: "乗っ取り耐性の自主訓練",
    desc: "自分に悪意ある指示文を試して、乗っ取られないかを月次で自己テストし結果を報告します。",
    kind: "bool",
    default: false,
    children: [
      {
        path: "proactive.injection_drill.day",
        label: "実行日",
        desc: "毎月何日に実行するか。",
        kind: "monthday",
        default: 5,
      },
      {
        path: "proactive.injection_drill.hour",
        label: "実行時刻",
        desc: "何時に実行するか。",
        kind: "hour",
        default: 12,
      },
    ],
  },
  {
    path: "proactive.ab_test.enabled",
    label: "話し方のA/B実験",
    desc: "プロンプトのA/B実験を評価し、はっきり差が出たときだけ採用を1回提案します（自動採用はしません）。",
    kind: "bool",
    default: false,
  },
  {
    path: "proactive.org_chart.enabled",
    label: "組織図の掲示",
    desc: "人間とAIの担当一覧図を月次で掲示します（前回の投稿を編集で上書きするので流れません）。",
    kind: "bool",
    default: false,
    children: [
      {
        path: "proactive.org_chart.day",
        label: "実行日",
        desc: "毎月何日に更新するか。",
        kind: "monthday",
        default: 1,
      },
      {
        path: "proactive.org_chart.hour",
        label: "実行時刻",
        desc: "何時に更新するか。",
        kind: "hour",
        default: 14,
      },
    ],
  },
  {
    path: "proactive.persona_checkup.enabled",
    label: "人格と実態のズレ点検",
    desc: "「人格定義」と「実際の発言」のズレを全AI分まとめて点検し、直し方を提案します。",
    kind: "bool",
    default: false,
    children: [
      {
        path: "proactive.persona_checkup.day",
        label: "実行日",
        desc: "毎月何日に点検するか。",
        kind: "monthday",
        default: 1,
      },
      {
        path: "proactive.persona_checkup.hour",
        label: "実行時刻",
        desc: "何時に点検するか。",
        kind: "hour",
        default: 15,
      },
    ],
  },
  {
    path: "proactive.self_audit.enabled",
    label: "その日の自己点検",
    desc: "夜に、その日の怪しい判断を自分で振り返って記録します。",
    kind: "bool",
    default: false,
    fixedNote: "実行時刻は23時でコード固定",
  },
  {
    path: "proactive.bias_check.enabled",
    label: "偏りの自己開示",
    desc: "「誰の話にはよく反応して、誰の話には反応していないか」の偏りを月次で自己申告します。",
    kind: "bool",
    default: false,
    fixedNote: "毎月1日16時でコード固定",
  },
  {
    path: "proactive.prophecy.enabled",
    label: "予測と答え合わせ",
    desc: "月初に前月の自分の予測を答え合わせし、今月分の予測を封印します。",
    kind: "bool",
    default: false,
    fixedNote: "毎月1日17時でコード固定",
  },
  {
    path: "proactive.study_group.enabled",
    label: "勉強会（学びの横展開）",
    desc: "個別に得た学びを他のAIへ広げるための勉強会を提案します。",
    kind: "bool",
    default: false,
    fixedNote: "毎月2日15時でコード固定",
  },
  {
    path: "proactive.ripple.enabled",
    label: "矛盾する過去の洗い出し",
    desc: "新しい決定が入ったとき、それと矛盾する過去の記録を横断で探して知らせます（✅で旧決定を無効化）。",
    kind: "bool",
    default: false,
  },
  {
    path: "proactive.comeback.enabled",
    label: "浦島さんへのあらすじ",
    desc: "長く休んでいた人が戻ってきたら、不在中に何があったかのあらすじを1回だけ渡します。",
    kind: "bool",
    default: false,
    children: [
      {
        path: "proactive.comeback.min_days",
        label: "何日休んだら対象か",
        desc: "これ以上の期間発言が無かった人を「浦島」とみなします。",
        kind: "int",
        default: 5,
        min: 1,
        max: 90,
        unit: "日",
      },
    ],
  },
  {
    path: "proactive.wiki.enabled",
    label: "Wikiの自動更新",
    desc: "新しい決定が関係するWikiページだけを編み直して、既存の投稿を上書きします（新規投稿はしません）。",
    kind: "bool",
    default: false,
  },
  {
    path: "proactive.news_watch.enabled",
    label: "業界ニュースの巡回",
    desc: "指定キーワードで業界ニュースを探し、週1で最大3件だけ報告します。",
    kind: "bool",
    default: false,
    children: [
      {
        path: "proactive.news_watch.keywords",
        label: "検索キーワード",
        desc: "空にするとこの機能は何もしません（実質オフ）。",
        kind: "stringList",
        default: [],
      },
      {
        path: "proactive.news_watch.weekday",
        label: "実行する曜日",
        desc: "ニュースを探す曜日。",
        kind: "weekday",
        default: 0,
        options: WEEKDAY_OPTIONS,
      },
      {
        path: "proactive.news_watch.hour",
        label: "実行時刻",
        desc: "ニュースを探す時刻。",
        kind: "hour",
        default: 9,
      },
    ],
  },
  {
    path: "proactive.newspaper.enabled",
    label: "社内新聞の発行",
    desc: "週1でタブロイド風の社内新聞を発行します（見出し＋挿し絵）。画像生成に失敗しても記事だけは必ず出ます。",
    kind: "bool",
    default: false,
    children: [
      {
        path: "proactive.newspaper.weekday",
        label: "発行する曜日",
        desc: "新聞を出す曜日。",
        kind: "weekday",
        default: 4,
        options: WEEKDAY_OPTIONS,
      },
      {
        path: "proactive.newspaper.hour",
        label: "発行時刻",
        desc: "新聞を出す時刻。",
        kind: "hour",
        default: 20,
      },
      {
        path: "proactive.newspaper.channel_id",
        label: "発行先チャンネル",
        desc: "未設定なら自分のホームチャンネルに出します。",
        kind: "string",
        default: null,
      },
      {
        path: "proactive.newspaper.image_gen.timeout_sec",
        label: "挿し絵の生成待ち時間",
        desc: "1枚の生成を何秒待つか。混雑時は30分かかることがあります。",
        kind: "int",
        default: 900,
        min: 30,
        max: 3600,
        unit: "秒",
      },
    ],
  },
];

export const PROACTIVE_GROUPS: SettingGroup[] = [
  {
    id: "proactive-common",
    label: "自発ループ（共通）",
    desc: "観察ループ全体にかかる設定。ここがオフなら下のサイクルはすべて動きません。",
    settings: COMMON,
  },
  {
    id: "proactive-cycles",
    label: "自発ループ",
    desc: "呼ばれなくても自分から動く機能。「シャドー」は実際には投稿せず、実行記録だけ残す安全な試運転モードです。",
    settings: CYCLES,
  },
];
